# !-----------------------------------------------------------------------------------------------!
#                       Welcome to the main configuration of ${project.name}
# !-----------------------------------------------------------------------------------------------!
#
#    For support and documentation, please visit:
#    - https://github.com/${author}/${project.name}/wiki
#
# !-----------------------------------------------------------------------------------------------!
#
#    1) COLOR CODES are supported with the '&' character.
#       - For usage, see http://minecraftwiki.net/wiki/Formatting_codes
#       - When you use them, place quotes around the message like this: "Hello &cworld."
#       - To use HEX colors, use #123456 syntax: "Hello #123456world."
#
#    2) TO HIDE any message, set it to 'none'.
#
#    3) For UNICODE CHARACTERS (smileys, symbols, ..), save the file in UTF-8 encoding. See
#       - https://github.com/${author}/${project.name}/wiki/Use-Right-Encoding
#
#    4) JSON is supported.
#       - For usage, see https://github.com/${author}/${project.name}/wiki/JSON
#
#    5) WHITELISTS can be turned into blacklists, by putting "@blacklist" on the first line.
#       - Doing such, filters will only apply for messages in those lists.
#
#    PS: Everything above applies for all files in ${project.name}/ folder.
#
# !-----------------------------------------------------------------------------------------------!

# -------------------------------------------------------------------------------------------------
# Allows you to enable the startup message.
# -------------------------------------------------------------------------------------------------
Silent_Start: false

# -------------------------------------------------------------------------------------------------
# Trolls section
# Here you can configure each aspect of the trolls.
# -------------------------------------------------------------------------------------------------
Trolls:

  # What commands should trigger the troll command?
  Command_Aliases: [ troll, tr ]

  # Filter trolls by permission.
  # If a player has the permission, they will be able to see and use the troll.
  Filter_By_Permission: true

  # The time in ticks that the player will be burning after being ignited.
  # 20 ticks = 1 second
  # 100 ticks = 5 seconds
  Ignite_Duration: 100

  # The power of the explosion when a player is exploded.
  # 1 is the default power.
  Explosion_Power: 1

  # Name of the scream sound.
  Scream_Sound: "GHAST_SCREAM"
  # Volume of the scream sound.
  # 1 is the default volume.
  Scream_Volume: 1

  # Ambush entity type.
  Ambush_Entity_Type: "PILLAGER"

  # Number of entities spawned when a player is ambushed.
  Ambush_Entity_Amount: 3

  # The item type and the amount used to fill the player's inventory.
  Fill_Inventory:
    # The item type used to fill the player's inventory.
    Material: "DEAD_BUSH"
    # The amount of items used to fill the player's inventory.
    Amount: 64

  # The message spammed in the player's chat.
  # You can use color codes and placeholders.
  Spam_Chat_Message: "You have been trolled!!! Muhahaa!"

  # How long does the blindness effect last in ticks.
  # 20 ticks = 1 second
  Blindness_Duration: 200

  # Radius of the random teleportation in blocks.
  Random_Teleport_Radius: 150

  # The message sent to the player when they are fake banned.
  Fake_Ban_Message: "&c&lYou have been banned for CHEATING!"

  # The height of the anvil rain in blocks.
  Anvil_Rain_Height: 20

  # Slowness amplifier.
  Slowness_Amplifier: 4

  # Levitation duration in ticks.
  Levitation_Amplifier: 4

  # Poison duration in ticks.
  Poison_Duration: 200

  # Poison amplifier.
  Poison_Amplifier: 2

  # Icon used in the troll menu.
  Icons:
    Launch_Player: "FIREWORK"
    Creeper_Hiss: "CREEPER_HEAD"
    Lightning_Strike: "TRIPWIRE_HOOK"
    Ignite_Player: "FLINT_AND_STEEL"
    Explode_Player: "TNT"
    Scream: "GHAST_TEAR"
    Ambush_Player: "ZOMBIE_SPAWN_EGG"
    Fill_Inventory: "CHEST"
    Dip_In_Lava: "LAVA_BUCKET"
    Clear_Inventory: "BARRIER"
    Spam_Chat: "PAPER"
    Turn_Player: "CLOCK"
    Drop_Inventory: "DROPPER"
    Fake_Op: "DIAMOND"
    Fake_Crash: "REDSTONE_BLOCK"
    Kill_Player: "SKELETON_SKULL"
    Slingshot_Player: "LEAD"
    Abyss: "BEDROCK"
    Blindness: "INK_SAC"
    Random_Teleport: "ENDER_PEARL"
    Lag_Behind: "Redstone"
    Pumpkin: "PUMPKIN"
    No_Item_Drop: "DROPPER"
    Open_Random_Inventory: "CHEST"
    Fake_Ban: "BARRIER"
    Cobweb: "COBWEB"
    No_Build_And_Break: "OAK_SIGN"
    Freeze_Player: "ICE"
    Teleport_To_Sun: "SUNFLOWER"
    Obsidian_Cage: "OBSIDIAN"
    Swap: "PURPLE_DYE"
    No_Chest: "CHEST"
    Anvil_Rain: "ANVIL"
    Shuffle_Inventory: "ENDER_CHEST"
    Spawn_Creeper: "CREEPER_HEAD"
    No_Item_Pickup: "FLOWER_POT"
    Disable_Gravity: "FEATHER"
    Disarm: "IRON_SWORD"
    Reverse_Messages: "BOOK"
    Send_Message: "PAPER"
    Potato: "POTATO"
    Slowness: "SUGAR"
    Levitation: "FEATHER"
    Clear_Armour: "IRON_CHESTPLATE"
    Near_Death: "REDSTONE"
    Poison: "SPIDER_EYE"
    Dip_In_Water: "WATER_BUCKET"
    Alone: "OAK_DOOR"
    Fireball: "FIRE_CHARGE"
# -------------------------------------------------------------------------------------------------
# The formats used in the {timestamp} and {location} variables. For help with timestamp, see:
# https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
# -------------------------------------------------------------------------------------------------
Timestamp_Format: "dd.MM.yyyy HH:mm:ss"
Location_Format: "{world} [{x}, {y}, {z}]"

# -------------------------------------------------------------------------------------------------
# What commands should trigger the main plugin command group?
# -------------------------------------------------------------------------------------------------
Command_Aliases: [ staxzstrolls ]

# -------------------------------------------------------------------------------------------------
# What language should we use for messages?
# -------------------------------------------------------------------------------------------------
Locale: en

# -------------------------------------------------------------------------------------------------
# The prefix used in front of most chat or console messages.
# -------------------------------------------------------------------------------------------------
Prefix: "&8[&a${project.name}&8]&7 "

# -------------------------------------------------------------------------------------------------
# Time of some plugin's operations is measured.
# We log a console message if an operation takes over the time below (milliseconds).
# Set to -1 to disable.
# -------------------------------------------------------------------------------------------------
Log_Lag_Over_Milis: 100

# -------------------------------------------------------------------------------------------------
# List of section names that will print informative messages about this plugin's features.
# The Debugger class utilizes this key and will only print messages for sections enabled below.
# -------------------------------------------------------------------------------------------------
Debug: [ ]

# -------------------------------------------------------------------------------------------------
# Do not change this value, otherwise it will corrupt your plugin installation!
# -------------------------------------------------------------------------------------------------
Version: 1