# !-----------------------------------------------------------------------------------------------!
#                       Welcome to the main configuration of ${project.name}
# !-----------------------------------------------------------------------------------------------!
#
#    For support and documentation, please visit:
#    - https://github.com/${author}/${project.name}-public/wiki
#
# !-----------------------------------------------------------------------------------------------!
#
#    1) COLOR CODES are supported with the '&' character.
#       - For usage, see http://minecraftwiki.net/wiki/Formatting_codes
#       - When you use them, place quotes around the message like this: "Hello &cworld."
#       - To use HEX colors, use #123456 syntax: "Hello #123456world."
#
#    2) For UNICODE CHARACTERS (smileys, symbols, ..), save the file in UTF-8 encoding (default).
#
# !-----------------------------------------------------------------------------------------------!

# -------------------------------------------------------------------------------------------------
# Trolls section
#
# Here you can configure each aspect of the trolls.
# -------------------------------------------------------------------------------------------------
Trolls:

  # What commands should trigger the troll command?
  Command_Aliases: [ troll, tr ]

  # Should we ignore the plebtrolls.immune permission?
  Ignore_Immunity: true

  # Should we log all executed trolls in the console?
  Log_Trolls: true

  # If enabled, we will only show trolls that the player has permission for.
  Filter_By_Permission: false

  # For how long should we ignite the player in ticks?
  # 20 ticks = 1 second
  Ignite_Duration: 100

  # With how much power we should explode the player?
  Explosion_Power: 1

  # Which sound should we play during th scream troll?
  # For all available sounds, see: https://is.gd/bHuypT
  Scream_Sound: "WITHER_IDLE"

  # How loud should the scream sound be?
  # 1 is the default volume.
  Scream_Volume: 3

  # What type of entity should be spawned when a player is ambushed?
  # For all available entities, see: https://is.gd/hmC0XM
  Ambush_Entity_Type: "ZOMBIE"

  # How many entities should be spawned when a player is ambushed?
  Ambush_Entity_Amount: 3

  # When replacing messages, the plugin will replace the original message with one of these.
  Replace_Messages:
    - "I am such a noob!"
    - "I am a cheater!"
    - "I am mom's favorite!"
    - "People say I stink!"
    - "I am such bad at this game!"

  # Settings for the Fill_Inventory troll.
  Fill_Inventory:
    # With what material should we fill the player's inventory?
    Material: "DEAD_BUSH"
    # How big will be each stack?
    Amount: 64

  # With what message should we spam the player's chat?
  Spam_Chat_Message: "You have been trolled!!! Muhahaa!"

  # How big should the random teleport radius be?
  Random_Teleport_Radius: 150

  # What fake ban message should we send to the player?
  Fake_Ban_Message: "&c&lYou have been banned for CHEATING!"

  # How high above the player should we spawn the anvils?
  Anvil_Rain_Height: 20

  # How strong should the slowness be?
  Slowness_Amplifier: 4

  # How strong should the levitation be?
  Levitation_Amplifier: 4

  # How long should the poison last in ticks?
  # 20 ticks = 1 second
  Poison_Duration: 200

  # How strong should the poison be?
  Poison_Amplifier: 2

  # How many cows should be spawned in the stampede troll?
  Stampede_Amount: 25

  # How many hounds should be spawned in the hound attack troll?
  Hound_Attack_Amount: 3

  # Icon used in the troll menu.
  Icons:
    Launch_Player: "FIREWORK"
    Creeper_Hiss: "CREEPER_HEAD"
    Lightning_Strike: "TRIPWIRE_HOOK"
    Ignite_Player: "FLINT_AND_STEEL"
    Explode_Player: "TNT"
    Scream: "GHAST_TEAR"
    Ambush_Player: "ZOMBIE_SPAWN_EGG"
    Fill_Inventory: "CHEST"
    Dip_In_Lava: "LAVA_BUCKET"
    Clear_Inventory: "BARRIER"
    Spam_Chat: "PAPER"
    Turn_Player: "CLOCK"
    Drop_Inventory: "DROPPER"
    Fake_Op: "DIAMOND"
    Fake_Crash: "REDSTONE_BLOCK"
    Kill_Player: "SKELETON_SKULL"
    Slingshot_Player: "LEAD"
    Abyss: "BEDROCK"
    Blindness: "INK_SAC"
    Random_Teleport: "ENDER_PEARL"
    Lag_Behind: "REDSTONE"
    Pumpkin: "PUMPKIN"
    No_Item_Drop: "HOPPER"
    Open_Random_Inventory: "CHEST"
    Fake_Ban: "COMMAND_BLOCK"
    Cobweb: "COBWEB"
    No_Build_And_Break: "OAK_SIGN"
    Freeze_Player: "ICE"
    Teleport_To_Sun: "SUNFLOWER"
    Obsidian_Cage: "OBSIDIAN"
    Swap: "PURPLE_DYE"
    No_Chest: "TRAPPED_CHEST"
    Anvil_Rain: "ANVIL"
    Shuffle_Inventory: "ENDER_CHEST"
    Spawn_Creeper: "FIREWORK_STAR"
    No_Item_Pickup: "FEATHER"
    Disable_Gravity: "FEATHER"
    Disarm: "IRON_SWORD"
    Reverse_Messages: "BOOK"
    Send_Message: "WRITTEN_BOOK"
    Potato: "POTATO"
    Slowness: "SUGAR"
    Levitation: "SHULKER_SHELL"
    Clear_Armour: "IRON_CHESTPLATE"
    Near_Death: "REDSTONE"
    Poison: "SPIDER_EYE"
    Dip_In_Water: "WATER_BUCKET"
    Alone: "OAK_DOOR"
    Fireball: "FIRE_CHARGE"
    Stampede: "COW_SPAWN_EGG"
    Suffocate: "SAND"
    Hound_Attack: "BONE"
    Lock_Hand: "IRON_NUGGET"
    Teleport_All: "CHORUS_FRUIT"
    Fake_Money: "GOLD_INGOT"
    Ring_Of_Fire: "BLAZE_POWDER"
    Tnt_Trap: "LEVER"
    Explode_Block: "GUNPOWDER"
    Gibberish_Messages: "WRITABLE_BOOK"
    Replace_Messages: "MAP"
    Guardian: "PRISMARINE_SHARD"

# -------------------------------------------------------------------------------------------------
# Tool section
# Here you can configure tools, which can be used to troll players.
# -------------------------------------------------------------------------------------------------
Tool:
  # What commands should trigger the tools command?
  Command_Aliases: [ trolltools, tt ]

  # What material should be used for the button which opens the tool menu?
  Tool_Menu_Material: "CHEST"

  # Settings for each tool.
  Smite_Tool:
    Material: "BLAZE_ROD"
    Name: "&6Smite"
    Lore:
      - ""
      - "&7Click to summon a lightning."
  Explode_Tool:
    Material: "STICK"
    Name: "&cExplode"
    Lore:
      - ""
      - "&7Click to create explosion."
    # With how much power we should make the explosion?
    Power: 4
  Repulsor_Tool:
    Material: "IRON_SWORD"
    Name: "&bRepulsor"
    Lore:
      - ""
      - "&7Click to repulse players and blocks."

    # How big should the repulsion radius be?
    Radius: 5
    # How strong should the repulsion be?
    Force: 1
    # Should we play a sound when using the tool?
    Play_Sound: true
    # What sound should we play?
    Sound: "ENTITY_ENDERMAN_TELEPORT"
  Spawn_Creeper_Tool:
    Material: "CREEPER_HEAD"
    Name: "&aSpawn Creeper"
    Lore:
      - ""
      - "&7Click to spawn a creeper."

# -------------------------------------------------------------------------------------------------
# The formats used in the {timestamp} and {location} variables. For help with timestamp, see:
# https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
# -------------------------------------------------------------------------------------------------
Timestamp_Format: "dd.MM.yyyy HH:mm:ss"
Location_Format: "{world} [{x}, {y}, {z}]"

# -------------------------------------------------------------------------------------------------
# What commands should trigger the main plugin command group?
# -------------------------------------------------------------------------------------------------
Command_Aliases: [ plebtrolls ]

# -------------------------------------------------------------------------------------------------
# What language should we use for messages? If it exists, the language file will be copied
# to your messages/ folder where you can edit it.
# See tutorial here: https://github.com/${author}/${project.name}-public/wiki/Localization
#
# AVAILABLE TRANSLATIONS:
#                  - en (English)
#                  - de (German)
#                  - cs (Czech)
#
# If you wish to share your translation, feel free to submit it on our github
# by opening a new issue: https://github.com/${author}/${project.name}-public/issues/new
# You will be credited in this file, like our other kind translators, and in the update log!
# ------------------------------------------------------------------------------------------
Locale: en

# -------------------------------------------------------------------------------------------------
# The prefix used in front of most chat or console messages.
# -------------------------------------------------------------------------------------------------
Prefix: "&8[&a${project.name}&8]&7 "

# -------------------------------------------------------------------------------------------------
# Time of some plugin's operations is measured.
# We log a console message if an operation takes over the time below (milliseconds).
# Set to -1 to disable.
# -------------------------------------------------------------------------------------------------
Log_Lag_Over_Milis: 100

# -------------------------------------------------------------------------------------------------
# List of section names that will print informative messages about their features.
# -------------------------------------------------------------------------------------------------
Debug: [ ]

# -------------------------------------------------------------------------------------------------
# Do not change this value, otherwise it will corrupt your plugin installation!
# -------------------------------------------------------------------------------------------------
Version: 1