# !-----------------------------------------------------------------------------------------------!
#                       Welcome to the main configuration of ${project.name}
# !-----------------------------------------------------------------------------------------------!
#
#    For support and documentation, please visit:
#    - https://github.com/${author}/${project.name}/wiki
#
# !-----------------------------------------------------------------------------------------------!
#
#    1) COLOR CODES are supported with the '&' character.
#       - For usage, see http://minecraftwiki.net/wiki/Formatting_codes
#       - When you use them, place quotes around the message like this: "Hello &cworld."
#       - To use HEX colors, use #123456 syntax: "Hello #123456world."
#
#    2) TO HIDE any message, set it to 'none'.
#
#    3) For UNICODE CHARACTERS (smileys, symbols, ..), save the file in UTF-8 encoding. See
#       - https://github.com/${author}/${project.name}/wiki/Use-Right-Encoding
#
#    4) JSON is supported.
#       - For usage, see https://github.com/${author}/${project.name}/wiki/JSON
#
#    5) WHITELISTS can be turned into blacklists, by putting "@blacklist" on the first line.
#       - Doing such, filters will only apply for messages in those lists.
#
#    PS: Everything above applies for all files in ${project.name}/ folder.
#
# !-----------------------------------------------------------------------------------------------!

# -------------------------------------------------------------------------------------------------
# Allows you to enable the startup message.
# -------------------------------------------------------------------------------------------------
Silent_Start: false

# -------------------------------------------------------------------------------------------------
# Trolls section
# -------------------------------------------------------------------------------------------------
Trolls:
  # The time in ticks that the player will be burning after being ignited.
  # 20 ticks = 1 second
  # 100 ticks = 5 seconds
  Ignite_Duration: 100

  # The power of the explosion when a player is exploded.
  # 1 is the default power.
  Explosion_Power: 1

  # Name of the scream sound.
  Scream_Sound: "GHAST_SCREAM"
  # Volume of the scream sound.
  # 1 is the default volume.
  Scream_Volume: 1

  # Icon used in the troll menu.
  Icons:
    Launch_Player: "FIREWORK"
    Creeper_Hiss: "CREEPER_HEAD"
    Lightning_Strike: "TRIPWIRE_HOOK"
    Ignite_Player: "FLINT_AND_STEEL"
    Explode_Player: "TNT"
    Scream: "GHAST_TEAR"
# -------------------------------------------------------------------------------------------------
# The formats used in the {timestamp} and {location} variables. For help with timestamp, see:
# https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
# -------------------------------------------------------------------------------------------------
Timestamp_Format: "dd.MM.yyyy HH:mm:ss"
Location_Format: "{world} [{x}, {y}, {z}]"

# -------------------------------------------------------------------------------------------------
# What commands should trigger the main plugin command group?
# -------------------------------------------------------------------------------------------------
Command_Aliases: [ staxzstrolls ]

# -------------------------------------------------------------------------------------------------
# What language should we use for messages?
# -------------------------------------------------------------------------------------------------
Locale: en

# -------------------------------------------------------------------------------------------------
# The prefix used in front of most chat or console messages.
# -------------------------------------------------------------------------------------------------
Prefix: "&8[&a${project.name}&8]&7 "

# -------------------------------------------------------------------------------------------------
# Time of some plugin's operations is measured.
# We log a console message if an operation takes over the time below (milliseconds).
# Set to -1 to disable.
# -------------------------------------------------------------------------------------------------
Log_Lag_Over_Milis: 100

# -------------------------------------------------------------------------------------------------
# List of section names that will print informative messages about this plugin's features.
# The Debugger class utilizes this key and will only print messages for sections enabled below.
# -------------------------------------------------------------------------------------------------
Debug: [ ]

# -------------------------------------------------------------------------------------------------
# Do not change this value, otherwise it will corrupt your plugin installation!
# -------------------------------------------------------------------------------------------------
Version: 1